defmodule Panopticon.Stories do

  def fetch_all_stories() do
    list_stores()
  end

  def list_stores do
    [
      %{
        active_lock_reason: nil,
        assignee: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/2063848?v=4",
          events_url: "https://api.github.com/users/thardeck/events{/privacy}",
          followers_url: "https://api.github.com/users/thardeck/followers",
          following_url: "https://api.github.com/users/thardeck/following{/other_user}",
          gists_url: "https://api.github.com/users/thardeck/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/thardeck",
          id: 2063848,
          login: "thardeck",
          node_id: "MDQ6VXNlcjIwNjM4NDg=",
          organizations_url: "https://api.github.com/users/thardeck/orgs",
          received_events_url: "https://api.github.com/users/thardeck/received_events",
          repos_url: "https://api.github.com/users/thardeck/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/thardeck/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/thardeck/subscriptions",
          type: "User",
          url: "https://api.github.com/users/thardeck"
        },
        assignees: [
          %{
            avatar_url: "https://avatars3.githubusercontent.com/u/2063848?v=4",
            events_url: "https://api.github.com/users/thardeck/events{/privacy}",
            followers_url: "https://api.github.com/users/thardeck/followers",
            following_url: "https://api.github.com/users/thardeck/following{/other_user}",
            gists_url: "https://api.github.com/users/thardeck/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/thardeck",
            id: 2063848,
            login: "thardeck",
            node_id: "MDQ6VXNlcjIwNjM4NDg=",
            organizations_url: "https://api.github.com/users/thardeck/orgs",
            received_events_url: "https://api.github.com/users/thardeck/received_events",
            repos_url: "https://api.github.com/users/thardeck/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/thardeck/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/thardeck/subscriptions",
            type: "User",
            url: "https://api.github.com/users/thardeck"
          }
        ],
        author_association: "CONTRIBUTOR",
        body: "The SUSE .net buildpack was not updated since April because there are issues in our .net update pipeline.\r\nhttps://github.com/SUSE/cf-dotnet-core-buildpack/releases\r\n\r\n## Acceptance criteria\r\n* The latest .net upstream buildpack is also available for the SUSE stack",
        closed_at: nil,
        comments: 0,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1284/comments",
        created_at: "2020-09-03T13:07:54Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1284/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/1284",
        id: 691956143,
        labels: [
          %{
            color: "e65c00",
            default: false,
            description: "",
            id: 1709895209,
            name: "Priority: High",
            node_id: "MDU6TGFiZWwxNzA5ODk1MjA5",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20High"
          },
          %{
            color: "e6b800",
            default: false,
            description: "",
            id: 1709902801,
            name: "Type: Maintenance",
            node_id: "MDU6TGFiZWwxNzA5OTAyODAx",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20Maintenance"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1284/labels{/name}",
        locked: false,
        milestone: nil,
        node_id: "MDU6SXNzdWU2OTE5NTYxNDM=",
        number: 1284,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "Update SUSE .net buildpack",
        updated_at: "2020-09-11T11:23:36Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1284",
        user: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/2063848?v=4",
          events_url: "https://api.github.com/users/thardeck/events{/privacy}",
          followers_url: "https://api.github.com/users/thardeck/followers",
          following_url: "https://api.github.com/users/thardeck/following{/other_user}",
          gists_url: "https://api.github.com/users/thardeck/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/thardeck",
          id: 2063848,
          login: "thardeck",
          node_id: "MDQ6VXNlcjIwNjM4NDg=",
          organizations_url: "https://api.github.com/users/thardeck/orgs",
          received_events_url: "https://api.github.com/users/thardeck/received_events",
          repos_url: "https://api.github.com/users/thardeck/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/thardeck/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/thardeck/subscriptions",
          type: "User",
          url: "https://api.github.com/users/thardeck"
        }
      },
      %{
        active_lock_reason: nil,
        assignee: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/2063848?v=4",
          events_url: "https://api.github.com/users/thardeck/events{/privacy}",
          followers_url: "https://api.github.com/users/thardeck/followers",
          following_url: "https://api.github.com/users/thardeck/following{/other_user}",
          gists_url: "https://api.github.com/users/thardeck/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/thardeck",
          id: 2063848,
          login: "thardeck",
          node_id: "MDQ6VXNlcjIwNjM4NDg=",
          organizations_url: "https://api.github.com/users/thardeck/orgs",
          received_events_url: "https://api.github.com/users/thardeck/received_events",
          repos_url: "https://api.github.com/users/thardeck/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/thardeck/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/thardeck/subscriptions",
          type: "User",
          url: "https://api.github.com/users/thardeck"
        },
        assignees: [
          %{
            avatar_url: "https://avatars3.githubusercontent.com/u/2063848?v=4",
            events_url: "https://api.github.com/users/thardeck/events{/privacy}",
            followers_url: "https://api.github.com/users/thardeck/followers",
            following_url: "https://api.github.com/users/thardeck/following{/other_user}",
            gists_url: "https://api.github.com/users/thardeck/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/thardeck",
            id: 2063848,
            login: "thardeck",
            node_id: "MDQ6VXNlcjIwNjM4NDg=",
            organizations_url: "https://api.github.com/users/thardeck/orgs",
            received_events_url: "https://api.github.com/users/thardeck/received_events",
            repos_url: "https://api.github.com/users/thardeck/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/thardeck/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/thardeck/subscriptions",
            type: "User",
            url: "https://api.github.com/users/thardeck"
          }
        ],
        author_association: "MEMBER",
        body: "## Acceptance Criteria\r\n\r\n- update the buildpacks (SLE15) bump pipeline to write to the new files\r\n- update the stemcell bump pipeline to write to the new files\r\n- pause the pipelines that bump stuff for SCF\r\n- use https://www.conventionalcommits.org/en/v1.0.0/ structure for prs\r\n\r\n**Files**\r\nhttps://github.com/cloudfoundry-incubator/kubecf/blob/master/chart/config/sle15.yaml\r\n\r\nFollow-up of #1086, needed for #1164",
        closed_at: nil,
        comments: 1,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1262/comments",
        created_at: "2020-08-27T16:32:38Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1262/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/1262",
        id: 687381766,
        labels: [
          %{
            color: "e60000",
            default: false,
            description: "",
            id: 1709894520,
            name: "Priority: Critical",
            node_id: "MDU6TGFiZWwxNzA5ODk0NTIw",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20Critical"
          },
          %{
            color: "f0dc59",
            default: false,
            description: "",
            id: 1934824810,
            name: "Size: 5",
            node_id: "MDU6TGFiZWwxOTM0ODI0ODEw",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Size:%205"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1262/labels{/name}",
        locked: false,
        milestone: nil,
        node_id: "MDU6SXNzdWU2ODczODE3NjY=",
        number: 1262,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "Update pipelines that bump stemcells and buildpacks to update the new locations",
        updated_at: "2020-09-11T11:12:52Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1262",
        user: %{
          avatar_url: "https://avatars1.githubusercontent.com/u/918484?v=4",
          events_url: "https://api.github.com/users/viovanov/events{/privacy}",
          followers_url: "https://api.github.com/users/viovanov/followers",
          following_url: "https://api.github.com/users/viovanov/following{/other_user}",
          gists_url: "https://api.github.com/users/viovanov/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/viovanov",
          id: 918484,
          login: "viovanov",
          node_id: "MDQ6VXNlcjkxODQ4NA==",
          organizations_url: "https://api.github.com/users/viovanov/orgs",
          received_events_url: "https://api.github.com/users/viovanov/received_events",
          repos_url: "https://api.github.com/users/viovanov/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/viovanov/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/viovanov/subscriptions",
          type: "User",
          url: "https://api.github.com/users/viovanov"
        }
      },
      %{
        active_lock_reason: nil,
        assignee: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/2196685?v=4",
          events_url: "https://api.github.com/users/viccuad/events{/privacy}",
          followers_url: "https://api.github.com/users/viccuad/followers",
          following_url: "https://api.github.com/users/viccuad/following{/other_user}",
          gists_url: "https://api.github.com/users/viccuad/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/viccuad",
          id: 2196685,
          login: "viccuad",
          node_id: "MDQ6VXNlcjIxOTY2ODU=",
          organizations_url: "https://api.github.com/users/viccuad/orgs",
          received_events_url: "https://api.github.com/users/viccuad/received_events",
          repos_url: "https://api.github.com/users/viccuad/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/viccuad/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/viccuad/subscriptions",
          type: "User",
          url: "https://api.github.com/users/viccuad"
        },
        assignees: [
          %{
            avatar_url: "https://avatars3.githubusercontent.com/u/2196685?v=4",
            events_url: "https://api.github.com/users/viccuad/events{/privacy}",
            followers_url: "https://api.github.com/users/viccuad/followers",
            following_url: "https://api.github.com/users/viccuad/following{/other_user}",
            gists_url: "https://api.github.com/users/viccuad/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/viccuad",
            id: 2196685,
            login: "viccuad",
            node_id: "MDQ6VXNlcjIxOTY2ODU=",
            organizations_url: "https://api.github.com/users/viccuad/orgs",
            received_events_url: "https://api.github.com/users/viccuad/received_events",
            repos_url: "https://api.github.com/users/viccuad/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/viccuad/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/viccuad/subscriptions",
            type: "User",
            url: "https://api.github.com/users/viccuad"
          }
        ],
        author_association: "MEMBER",
        body: "**Is your feature request related to a problem? Please describe.**\r\n\r\nSince around a week, the upgrade job seems to be failing:\r\nhttps://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/upgrade-test-master/builds/58\r\nhttps://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/upgrade-test-pr/builds/98\r\n\r\n**Describe the solution you'd like**\r\n\r\nMake the upgrade job green again, and mark its status as required.\r\n\r\n**Describe alternatives you've considered**\r\n\r\nNone\r\n\r\n**Additional context**\r\n\r\n",
        closed_at: nil,
        comments: 6,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1190/comments",
        created_at: "2020-08-04T15:21:24Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1190/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/1190",
        id: 672876546,
        labels: [
          %{
            color: "e65c00",
            default: false,
            description: "",
            id: 1709895209,
            name: "Priority: High",
            node_id: "MDU6TGFiZWwxNzA5ODk1MjA5",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20High"
          },
          %{
            color: "d73a4a",
            default: false,
            description: "Something isn't working",
            id: 1621674803,
            name: "Type: Bug",
            node_id: "MDU6TGFiZWwxNjIxNjc0ODAz",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20Bug"
          },
          %{
            color: "9346d6",
            default: false,
            description: "Issues for working on the project's CI pipelines",
            id: 1624006848,
            name: "Type: CI",
            node_id: "MDU6TGFiZWwxNjI0MDA2ODQ4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20CI"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1190/labels{/name}",
        locked: false,
        milestone: %{
          closed_at: nil,
          closed_issues: 29,
          created_at: "2020-06-26T10:04:38Z",
          creator: %{
            avatar_url: "https://avatars2.githubusercontent.com/u/904062?v=4",
            events_url: "https://api.github.com/users/fargozhu/events{/privacy}",
            followers_url: "https://api.github.com/users/fargozhu/followers",
            following_url: "https://api.github.com/users/fargozhu/following{/other_user}",
            gists_url: "https://api.github.com/users/fargozhu/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/fargozhu",
            id: 904062,
            login: "fargozhu",
            node_id: "MDQ6VXNlcjkwNDA2Mg==",
            organizations_url: "https://api.github.com/users/fargozhu/orgs",
            received_events_url: "https://api.github.com/users/fargozhu/received_events",
            repos_url: "https://api.github.com/users/fargozhu/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/fargozhu/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/fargozhu/subscriptions",
            type: "User",
            url: "https://api.github.com/users/fargozhu"
          },
          description: "",
          due_on: nil,
          html_url: "https://github.com/cloudfoundry-incubator/kubecf/milestone/12",
          id: 5585831,
          labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12/labels",
          node_id: "MDk6TWlsZXN0b25lNTU4NTgzMQ==",
          number: 12,
          open_issues: 18,
          state: "open",
          title: "jumanji",
          updated_at: "2020-09-11T12:14:59Z",
          url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12"
        },
        node_id: "MDU6SXNzdWU2NzI4NzY1NDY=",
        number: 1190,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "Investigate regression on CI upgrade job",
        updated_at: "2020-09-09T16:04:00Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1190",
        user: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/2196685?v=4",
          events_url: "https://api.github.com/users/viccuad/events{/privacy}",
          followers_url: "https://api.github.com/users/viccuad/followers",
          following_url: "https://api.github.com/users/viccuad/following{/other_user}",
          gists_url: "https://api.github.com/users/viccuad/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/viccuad",
          id: 2196685,
          login: "viccuad",
          node_id: "MDQ6VXNlcjIxOTY2ODU=",
          organizations_url: "https://api.github.com/users/viccuad/orgs",
          received_events_url: "https://api.github.com/users/viccuad/received_events",
          repos_url: "https://api.github.com/users/viccuad/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/viccuad/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/viccuad/subscriptions",
          type: "User",
          url: "https://api.github.com/users/viccuad"
        }
      },
      %{
        active_lock_reason: nil,
        assignee: nil,
        assignees: [],
        author_association: "MEMBER",
        body: "We have 2 different pipelines that bump buildpacks in kubecf:\r\n\r\n1. whenever upstream releases a new buildpack we get a corresponding build for the SUSE buildpack with the latest stemcell at that point in time\r\n\r\n2. whenever there is a new release of the SUSE stemcell, all buildpacks bundled in kubecf get rebuilt on the new stemcell and CI will create a PR to update kubecf\r\n\r\nThe most pressing issue is that the pipeline in step 2 seems to only rebuild the version of the buildpack that is currently listed in kubecf. If there is a pending bump to the buildpack, that has not yet been merged, then this buildpack bump will get broken, unless we revert the stemcell bump for that particular buildpack version.\r\n\r\nFor example this has happened by merging #1157, which breaks both #1131 and #1135 \r\n\r\n```\r\n$ reg tags registry.suse.com/cap-staging/suse-ruby-buildpack\r\n...\r\nSLE_15_SP1-26.7-7.0.0_374.gb8e8e6af-1.8.19.1\r\nSLE_15_SP1-26.7-7.0.0_374.gb8e8e6af-1.8.21.1\r\nSLE_15_SP1-26.8-7.0.0_374.gb8e8e6af-1.8.19.1\r\nSLE_15_SP1-27.1-7.0.0_374.gb8e8e6af-1.8.19.1\r\n```\r\n\r\nThe whole rebuilding buildpack releases is not really necessary (explained in #1109). And we also don't seem to do it for the upstream buildpacks, but only for the SUSE ones.\r\n\r\nSo instead of somehow \"fixing\" this in the pipeline, I would like us to consider the proposal in #1109 \r\n\r\nAs a first step we could simply stop rebuilding buildpack images for stemcell upgrades. That would solve the immediate problem, but over time we may end up with multiple different stemcell layers in the various releases, which will increase the download times for the images. Therefore I would like the full proposal implemented, building buildpack images on alpine or scratch containers.",
        closed_at: nil,
        comments: 4,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1164/comments",
        created_at: "2020-07-24T18:45:14Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1164/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/1164",
        id: 665349688,
        labels: [
          %{
            color: "e65c00",
            default: false,
            description: "",
            id: 1709895209,
            name: "Priority: High",
            node_id: "MDU6TGFiZWwxNzA5ODk1MjA5",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20High"
          },
          %{
            color: "d73a4a",
            default: false,
            description: "Something isn't working",
            id: 1621674803,
            name: "Type: Bug",
            node_id: "MDU6TGFiZWwxNjIxNjc0ODAz",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20Bug"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1164/labels{/name}",
        locked: false,
        milestone: nil,
        node_id: "MDU6SXNzdWU2NjUzNDk2ODg=",
        number: 1164,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "SUSE buildpack stemcell bumps don't always support latest buildpacks",
        updated_at: "2020-09-04T07:31:39Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1164",
        user: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/78947?v=4",
          events_url: "https://api.github.com/users/jandubois/events{/privacy}",
          followers_url: "https://api.github.com/users/jandubois/followers",
          following_url: "https://api.github.com/users/jandubois/following{/other_user}",
          gists_url: "https://api.github.com/users/jandubois/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/jandubois",
          id: 78947,
          login: "jandubois",
          node_id: "MDQ6VXNlcjc4OTQ3",
          organizations_url: "https://api.github.com/users/jandubois/orgs",
          received_events_url: "https://api.github.com/users/jandubois/received_events",
          repos_url: "https://api.github.com/users/jandubois/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/jandubois/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/jandubois/subscriptions",
          type: "User",
          url: "https://api.github.com/users/jandubois"
        }
      },
      %{
        active_lock_reason: nil,
        assignee: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/78947?v=4",
          events_url: "https://api.github.com/users/jandubois/events{/privacy}",
          followers_url: "https://api.github.com/users/jandubois/followers",
          following_url: "https://api.github.com/users/jandubois/following{/other_user}",
          gists_url: "https://api.github.com/users/jandubois/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/jandubois",
          id: 78947,
          login: "jandubois",
          node_id: "MDQ6VXNlcjc4OTQ3",
          organizations_url: "https://api.github.com/users/jandubois/orgs",
          received_events_url: "https://api.github.com/users/jandubois/received_events",
          repos_url: "https://api.github.com/users/jandubois/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/jandubois/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/jandubois/subscriptions",
          type: "User",
          url: "https://api.github.com/users/jandubois"
        },
        assignees: [
          %{
            avatar_url: "https://avatars3.githubusercontent.com/u/78947?v=4",
            events_url: "https://api.github.com/users/jandubois/events{/privacy}",
            followers_url: "https://api.github.com/users/jandubois/followers",
            following_url: "https://api.github.com/users/jandubois/following{/other_user}",
            gists_url: "https://api.github.com/users/jandubois/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/jandubois",
            id: 78947,
            login: "jandubois",
            node_id: "MDQ6VXNlcjc4OTQ3",
            organizations_url: "https://api.github.com/users/jandubois/orgs",
            received_events_url: "https://api.github.com/users/jandubois/received_events",
            repos_url: "https://api.github.com/users/jandubois/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/jandubois/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/jandubois/subscriptions",
            type: "User",
            url: "https://api.github.com/users/jandubois"
          }
        ],
        author_association: "MEMBER",
        body: "Right now it is possible to override memory limits on a per-container basis, like this:\r\n\r\n```\r\noperations:\r\n  inline:\r\n  - type: replace\r\n    path: /instance_groups/name=log-cache/jobs/name=log-cache/properties/quarks?/bpm/processes/name=log-cache/limits/memory\r\n    value: 2G\r\n```\r\n\r\nBut it is impractical to expect the user to know the list of instance groups and jobs, that needs to be configured, and what a sensible memory limit would be for each.\r\n\r\nThis request if for:\r\n\r\n[ ] collect typical memory requirements for each job, verify them against possible defaults in the `bpm.yml` files, and then include them in kubecf.\r\n\r\n[ ] Provide a mechanism in kubecf to globally enable memory limits with the default settings\r\n\r\nThis request does not cover disk size limits. They are not supported by the bpm model, and not implemented by cf-operator.\r\n\r\n\r\n## Acceptance Criteria\r\n\r\nKubeCF should start and run CATS normally within these limits.\r\nCollect peak values from SUSE's sandbox and add 50% to that.\r\n\r\n",
        closed_at: nil,
        comments: 17,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1142/comments",
        created_at: "2020-07-21T03:19:40Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1142/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/1142",
        id: 662525158,
        labels: [
          %{
            color: "e65c00",
            default: false,
            description: "",
            id: 1709895209,
            name: "Priority: High",
            node_id: "MDU6TGFiZWwxNzA5ODk1MjA5",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20High"
          },
          %{
            color: "f08441",
            default: false,
            description: "",
            id: 1934826707,
            name: "Size: 8",
            node_id: "MDU6TGFiZWwxOTM0ODI2NzA3",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Size:%208"
          },
          %{
            color: "a2eeef",
            default: false,
            description: "New feature or request",
            id: 1621674806,
            name: "Type: Enhancement",
            node_id: "MDU6TGFiZWwxNjIxNjc0ODA2",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20Enhancement"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1142/labels{/name}",
        locked: false,
        milestone: nil,
        node_id: "MDU6SXNzdWU2NjI1MjUxNTg=",
        number: 1142,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "Implement default memory limits",
        updated_at: "2020-09-10T20:30:49Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1142",
        user: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/78947?v=4",
          events_url: "https://api.github.com/users/jandubois/events{/privacy}",
          followers_url: "https://api.github.com/users/jandubois/followers",
          following_url: "https://api.github.com/users/jandubois/following{/other_user}",
          gists_url: "https://api.github.com/users/jandubois/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/jandubois",
          id: 78947,
          login: "jandubois",
          node_id: "MDQ6VXNlcjc4OTQ3",
          organizations_url: "https://api.github.com/users/jandubois/orgs",
          received_events_url: "https://api.github.com/users/jandubois/received_events",
          repos_url: "https://api.github.com/users/jandubois/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/jandubois/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/jandubois/subscriptions",
          type: "User",
          url: "https://api.github.com/users/jandubois"
        }
      },
      %{
        active_lock_reason: nil,
        assignee: %{
          avatar_url: "https://avatars1.githubusercontent.com/u/2794419?v=4",
          events_url: "https://api.github.com/users/jimmykarily/events{/privacy}",
          followers_url: "https://api.github.com/users/jimmykarily/followers",
          following_url: "https://api.github.com/users/jimmykarily/following{/other_user}",
          gists_url: "https://api.github.com/users/jimmykarily/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/jimmykarily",
          id: 2794419,
          login: "jimmykarily",
          node_id: "MDQ6VXNlcjI3OTQ0MTk=",
          organizations_url: "https://api.github.com/users/jimmykarily/orgs",
          received_events_url: "https://api.github.com/users/jimmykarily/received_events",
          repos_url: "https://api.github.com/users/jimmykarily/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/jimmykarily/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/jimmykarily/subscriptions",
          type: "User",
          url: "https://api.github.com/users/jimmykarily"
        },
        assignees: [
          %{
            avatar_url: "https://avatars1.githubusercontent.com/u/2794419?v=4",
            events_url: "https://api.github.com/users/jimmykarily/events{/privacy}",
            followers_url: "https://api.github.com/users/jimmykarily/followers",
            following_url: "https://api.github.com/users/jimmykarily/following{/other_user}",
            gists_url: "https://api.github.com/users/jimmykarily/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/jimmykarily",
            id: 2794419,
            login: "jimmykarily",
            node_id: "MDQ6VXNlcjI3OTQ0MTk=",
            organizations_url: "https://api.github.com/users/jimmykarily/orgs",
            received_events_url: "https://api.github.com/users/jimmykarily/received_events",
            repos_url: "https://api.github.com/users/jimmykarily/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/jimmykarily/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/jimmykarily/subscriptions",
            type: "User",
            url: "https://api.github.com/users/jimmykarily"
          },
          %{
            avatar_url: "https://avatars2.githubusercontent.com/u/47635090?v=4",
            events_url: "https://api.github.com/users/jbuns/events{/privacy}",
            followers_url: "https://api.github.com/users/jbuns/followers",
            following_url: "https://api.github.com/users/jbuns/following{/other_user}",
            gists_url: "https://api.github.com/users/jbuns/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/jbuns",
            id: 47635090,
            login: "jbuns",
            node_id: "MDQ6VXNlcjQ3NjM1MDkw",
            organizations_url: "https://api.github.com/users/jbuns/orgs",
            received_events_url: "https://api.github.com/users/jbuns/received_events",
            repos_url: "https://api.github.com/users/jbuns/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/jbuns/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/jbuns/subscriptions",
            type: "User",
            url: "https://api.github.com/users/jbuns"
          }
        ],
        author_association: "COLLABORATOR",
        body: "**Is your feature request related to a problem? Please describe.**\r\nCATs fail on Eirini. We need to run only CATs that make sense and should be green when running on Eirini deployments.\r\n\r\n**Describe the solution you'd like**\r\nLook here on how this can be implemented:\r\n(https://github.com/SUSE/catapult/blob/master/modules/tests/kubecf-test.sh#L139). ",
        closed_at: nil,
        comments: 17,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1007/comments",
        created_at: "2020-06-11T09:39:53Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1007/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/1007",
        id: 636872856,
        labels: [
          %{
            color: "e60000",
            default: false,
            description: "",
            id: 1709894520,
            name: "Priority: Critical",
            node_id: "MDU6TGFiZWwxNzA5ODk0NTIw",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20Critical"
          },
          %{
            color: "f08441",
            default: false,
            description: "",
            id: 1934826707,
            name: "Size: 8",
            node_id: "MDU6TGFiZWwxOTM0ODI2NzA3",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Size:%208"
          },
          %{
            color: "296387",
            default: false,
            description: "Dependencies on other issues and/or pull requests",
            id: 1624005099,
            name: "Status: Blocked",
            node_id: "MDU6TGFiZWwxNjI0MDA1MDk5",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Status:%20Blocked"
          },
          %{
            color: "db2938",
            default: false,
            description: "Any issue which impedes pull requests",
            id: 1697045624,
            name: "Status: Contributor Pain",
            node_id: "MDU6TGFiZWwxNjk3MDQ1NjI0",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Status:%20Contributor%20Pain"
          },
          %{
            color: "9346d6",
            default: false,
            description: "Issues for working on the project's CI pipelines",
            id: 1624006848,
            name: "Type: CI",
            node_id: "MDU6TGFiZWwxNjI0MDA2ODQ4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20CI"
          },
          %{
            color: "9af99a",
            default: true,
            description: "Extra attention is needed",
            id: 1621674807,
            name: "help wanted",
            node_id: "MDU6TGFiZWwxNjIxNjc0ODA3",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/help%20wanted"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1007/labels{/name}",
        locked: false,
        milestone: %{
          closed_at: nil,
          closed_issues: 29,
          created_at: "2020-06-26T10:04:38Z",
          creator: %{
            avatar_url: "https://avatars2.githubusercontent.com/u/904062?v=4",
            events_url: "https://api.github.com/users/fargozhu/events{/privacy}",
            followers_url: "https://api.github.com/users/fargozhu/followers",
            following_url: "https://api.github.com/users/fargozhu/following{/other_user}",
            gists_url: "https://api.github.com/users/fargozhu/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/fargozhu",
            id: 904062,
            login: "fargozhu",
            node_id: "MDQ6VXNlcjkwNDA2Mg==",
            organizations_url: "https://api.github.com/users/fargozhu/orgs",
            received_events_url: "https://api.github.com/users/fargozhu/received_events",
            repos_url: "https://api.github.com/users/fargozhu/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/fargozhu/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/fargozhu/subscriptions",
            type: "User",
            url: "https://api.github.com/users/fargozhu"
          },
          description: "",
          due_on: nil,
          html_url: "https://github.com/cloudfoundry-incubator/kubecf/milestone/12",
          id: 5585831,
          labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12/labels",
          node_id: "MDk6TWlsZXN0b25lNTU4NTgzMQ==",
          number: 12,
          open_issues: 18,
          state: "open",
          title: "jumanji",
          updated_at: "2020-09-11T12:14:59Z",
          url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12"
        },
        node_id: "MDU6SXNzdWU2MzY4NzI4NTY=",
        number: 1007,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "Use proper options when running CATs on Eirini",
        updated_at: "2020-09-02T09:55:23Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/1007",
        user: %{
          avatar_url: "https://avatars1.githubusercontent.com/u/2794419?v=4",
          events_url: "https://api.github.com/users/jimmykarily/events{/privacy}",
          followers_url: "https://api.github.com/users/jimmykarily/followers",
          following_url: "https://api.github.com/users/jimmykarily/following{/other_user}",
          gists_url: "https://api.github.com/users/jimmykarily/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/jimmykarily",
          id: 2794419,
          login: "jimmykarily",
          node_id: "MDQ6VXNlcjI3OTQ0MTk=",
          organizations_url: "https://api.github.com/users/jimmykarily/orgs",
          received_events_url: "https://api.github.com/users/jimmykarily/received_events",
          repos_url: "https://api.github.com/users/jimmykarily/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/jimmykarily/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/jimmykarily/subscriptions",
          type: "User",
          url: "https://api.github.com/users/jimmykarily"
        }
      },
      %{
        active_lock_reason: nil,
        assignee: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/2420543?v=4",
          events_url: "https://api.github.com/users/mudler/events{/privacy}",
          followers_url: "https://api.github.com/users/mudler/followers",
          following_url: "https://api.github.com/users/mudler/following{/other_user}",
          gists_url: "https://api.github.com/users/mudler/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/mudler",
          id: 2420543,
          login: "mudler",
          node_id: "MDQ6VXNlcjI0MjA1NDM=",
          organizations_url: "https://api.github.com/users/mudler/orgs",
          received_events_url: "https://api.github.com/users/mudler/received_events",
          repos_url: "https://api.github.com/users/mudler/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/mudler/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/mudler/subscriptions",
          type: "User",
          url: "https://api.github.com/users/mudler"
        },
        assignees: [
          %{
            avatar_url: "https://avatars3.githubusercontent.com/u/2420543?v=4",
            events_url: "https://api.github.com/users/mudler/events{/privacy}",
            followers_url: "https://api.github.com/users/mudler/followers",
            following_url: "https://api.github.com/users/mudler/following{/other_user}",
            gists_url: "https://api.github.com/users/mudler/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/mudler",
            id: 2420543,
            login: "mudler",
            node_id: "MDQ6VXNlcjI0MjA1NDM=",
            organizations_url: "https://api.github.com/users/mudler/orgs",
            received_events_url: "https://api.github.com/users/mudler/received_events",
            repos_url: "https://api.github.com/users/mudler/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/mudler/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/mudler/subscriptions",
            type: "User",
            url: "https://api.github.com/users/mudler"
          }
        ],
        author_association: "NONE",
        body: "**Describe the bug**\r\nWhen deploying a golang app and the app exits due to an error, `cf logs` doesn't show the actual error from `stderr` but only provides the state of the app like:\r\n\r\n```\r\n   2020-05-25T02:33:58.89+0000 [API/0] OUT Process has crashed with type: \"web\"\r\n   2020-05-25T02:33:58.91+0000 [API/0] OUT App instance exited with guid e6320336-6585-4ebc-9b4e-9c859496d9a5 payload: {\"instance\"=>\"postgres-svc-broker-testrun-5d4ed6a624-0\", \"index\"=>0, \"cell_id\"=>\"\", \"reason\"=>\"CrashLoopBackOff\", \"exit_status\"=>1, \"exit_description\"=>\"Error\", \"crash_count\"=>5, \"crash_timestamp\"=>53, \"version\"=>\"089445c0-c45a-41b3-9317-f6de711fbc5a\"}\r\n   2020-05-25T02:36:50.00+0000 [API/0] OUT Process has crashed with type: \"web\"\r\n   2020-05-25T02:36:50.03+0000 [API/0] OUT App instance exited with guid e6320336-6585-4ebc-9b4e-9c859496d9a5 payload: {\"instance\"=>\"postgres-svc-broker-testrun-5d4ed6a624-0\", \"index\"=>0, \"cell_id\"=>\"\", \"reason\"=>\"Error\", \"exit_status\"=>1, \"exit_description\"=>\"Error\", \"crash_count\"=>6, \"crash_timestamp\"=>48, \"version\"=>\"089445c0-c45a-41b3-9317-f6de711fbc5a\"}\r\n   2020-05-25T02:36:58.89+0000 [API/0] OUT Process has crashed with type: \"web\"\r\n   2020-05-25T02:36:58.92+0000 [API/0] OUT App instance exited with guid e6320336-6585-4ebc-9b4e-9c859496d9a5 payload: {\"instance\"=>\"postgres-svc-broker-testrun-5d4ed6a624-0\", \"index\"=>0, \"cell_id\"=>\"\", \"reason\"=>\"CrashLoopBackOff\", \"exit_status\"=>1, \"exit_description\"=>\"Error\", \"crash_count\"=>6, \"crash_timestamp\"=>48, \"version\"=>\"089445c0-c45a-41b3-9317-f6de711fbc5a\"}\r\n```\r\n\r\nBut when I do a `kubectl logs` on the application container on `eirini`, the actual error is returned:\r\n\r\n```\r\ndavidc@x:~/codebase/postgres-svc-broker$ k logs postgres-svc-broker-testrun-5d4ed6a624-0 -p\r\nARGS: [/lifecycle/launch]\r\n2020/05/25 02:47:08 error retrieving vault-token from file: open /home/vcap/app/.vault-token: no such file or directory\r\n\r\n```\r\n\r\n**To Reproduce**\r\n- create a golang app\r\n- have the golang app fail immediately with a `log.Fatal()`\r\n- `cf push` app\r\n\r\n**Expected behavior**\r\n`cf logs` should return the actual application error\r\n\r\n**Environment**\r\n- kubecf chart: v2.2.1\r\n- cf-operator chart v4.5.6+0.gffc6f942\r\n- cf-cli 6.51.0+2acd15650.2020-04-07\r\n\r\n`kubecf` running with `values.yml`\r\n\r\n```\r\nsystem_domain: system.xxx\r\n\r\nkube:\r\n  service_cluster_ip_range: 10.0.0.0/16\r\n  pod_cluster_ip_range: 10.110.0.0/16\r\n\r\nfeatures:\r\n  eirini:\r\n    enabled: true\r\n\r\n```",
        closed_at: nil,
        comments: 2,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/923/comments",
        created_at: "2020-05-25T02:53:07Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/923/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/923",
        id: 624012190,
        labels: [
          %{
            color: "e65c00",
            default: false,
            description: "",
            id: 1709895209,
            name: "Priority: High",
            node_id: "MDU6TGFiZWwxNzA5ODk1MjA5",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20High"
          },
          %{
            color: "d73a4a",
            default: false,
            description: "Something isn't working",
            id: 1621674803,
            name: "Type: Bug",
            node_id: "MDU6TGFiZWwxNjIxNjc0ODAz",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20Bug"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/923/labels{/name}",
        locked: false,
        milestone: %{
          closed_at: nil,
          closed_issues: 29,
          created_at: "2020-06-26T10:04:38Z",
          creator: %{
            avatar_url: "https://avatars2.githubusercontent.com/u/904062?v=4",
            events_url: "https://api.github.com/users/fargozhu/events{/privacy}",
            followers_url: "https://api.github.com/users/fargozhu/followers",
            following_url: "https://api.github.com/users/fargozhu/following{/other_user}",
            gists_url: "https://api.github.com/users/fargozhu/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/fargozhu",
            id: 904062,
            login: "fargozhu",
            node_id: "MDQ6VXNlcjkwNDA2Mg==",
            organizations_url: "https://api.github.com/users/fargozhu/orgs",
            received_events_url: "https://api.github.com/users/fargozhu/received_events",
            repos_url: "https://api.github.com/users/fargozhu/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/fargozhu/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/fargozhu/subscriptions",
            type: "User",
            url: "https://api.github.com/users/fargozhu"
          },
          description: "",
          due_on: nil,
          html_url: "https://github.com/cloudfoundry-incubator/kubecf/milestone/12",
          id: 5585831,
          labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12/labels",
          node_id: "MDk6TWlsZXN0b25lNTU4NTgzMQ==",
          number: 12,
          open_issues: 18,
          state: "open",
          title: "jumanji",
          updated_at: "2020-09-11T12:14:59Z",
          url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12"
        },
        node_id: "MDU6SXNzdWU2MjQwMTIxOTA=",
        number: 923,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "cf logs does not display application error but kubectl logs on container does",
        updated_at: "2020-09-04T07:29:41Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/923",
        user: %{
          avatar_url: "https://avatars2.githubusercontent.com/u/68039?v=4",
          events_url: "https://api.github.com/users/davidchua/events{/privacy}",
          followers_url: "https://api.github.com/users/davidchua/followers",
          following_url: "https://api.github.com/users/davidchua/following{/other_user}",
          gists_url: "https://api.github.com/users/davidchua/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/davidchua",
          id: 68039,
          login: "davidchua",
          node_id: "MDQ6VXNlcjY4MDM5",
          organizations_url: "https://api.github.com/users/davidchua/orgs",
          received_events_url: "https://api.github.com/users/davidchua/received_events",
          repos_url: "https://api.github.com/users/davidchua/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/davidchua/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/davidchua/subscriptions",
          type: "User",
          url: "https://api.github.com/users/davidchua"
        }
      },
      %{
        active_lock_reason: nil,
        assignee: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/78947?v=4",
          events_url: "https://api.github.com/users/jandubois/events{/privacy}",
          followers_url: "https://api.github.com/users/jandubois/followers",
          following_url: "https://api.github.com/users/jandubois/following{/other_user}",
          gists_url: "https://api.github.com/users/jandubois/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/jandubois",
          id: 78947,
          login: "jandubois",
          node_id: "MDQ6VXNlcjc4OTQ3",
          organizations_url: "https://api.github.com/users/jandubois/orgs",
          received_events_url: "https://api.github.com/users/jandubois/received_events",
          repos_url: "https://api.github.com/users/jandubois/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/jandubois/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/jandubois/subscriptions",
          type: "User",
          url: "https://api.github.com/users/jandubois"
        },
        assignees: [
          %{
            avatar_url: "https://avatars3.githubusercontent.com/u/78947?v=4",
            events_url: "https://api.github.com/users/jandubois/events{/privacy}",
            followers_url: "https://api.github.com/users/jandubois/followers",
            following_url: "https://api.github.com/users/jandubois/following{/other_user}",
            gists_url: "https://api.github.com/users/jandubois/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/jandubois",
            id: 78947,
            login: "jandubois",
            node_id: "MDQ6VXNlcjc4OTQ3",
            organizations_url: "https://api.github.com/users/jandubois/orgs",
            received_events_url: "https://api.github.com/users/jandubois/received_events",
            repos_url: "https://api.github.com/users/jandubois/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/jandubois/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/jandubois/subscriptions",
            type: "User",
            url: "https://api.github.com/users/jandubois"
          }
        ],
        author_association: "MEMBER",
        body: "`sizing.bits.instances` and `sizing.eirini.instances` are defined in `values.yaml`, but not used for anything. The subcharts don't have any mechanism to set a replica count.\r\n\r\n## Acceptance Criteria\r\n\r\n- [ ] bits should have settings in values.yaml to control instance count\r\n- [ ] eirini should have settings in values.yaml to control instance count\r\n- [ ] eirinix should have settings in values.yaml to control instance count\r\n- [ ] remove any unused sizing configs from the kubecf values.yaml\r\n- [ ] test to see if each of the components can be HA\r\n- [ ] document configuration for HA eirini\r\n\r\n\r\n## Relates\r\n\r\nhttps://github.com/cloudfoundry-incubator/kubecf/issues/1277",
        closed_at: nil,
        comments: 1,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/905/comments",
        created_at: "2020-05-20T20:46:38Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/905/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/905",
        id: 622073974,
        labels: [
          %{
            color: "e65c00",
            default: false,
            description: "",
            id: 1709895209,
            name: "Priority: High",
            node_id: "MDU6TGFiZWwxNzA5ODk1MjA5",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20High"
          },
          %{
            color: "f08441",
            default: false,
            description: "",
            id: 1934826707,
            name: "Size: 8",
            node_id: "MDU6TGFiZWwxOTM0ODI2NzA3",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Size:%208"
          },
          %{
            color: "a2eeef",
            default: false,
            description: "New feature or request",
            id: 1621674806,
            name: "Type: Enhancement",
            node_id: "MDU6TGFiZWwxNjIxNjc0ODA2",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20Enhancement"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/905/labels{/name}",
        locked: false,
        milestone: %{
          closed_at: nil,
          closed_issues: 29,
          created_at: "2020-06-26T10:04:38Z",
          creator: %{
            avatar_url: "https://avatars2.githubusercontent.com/u/904062?v=4",
            events_url: "https://api.github.com/users/fargozhu/events{/privacy}",
            followers_url: "https://api.github.com/users/fargozhu/followers",
            following_url: "https://api.github.com/users/fargozhu/following{/other_user}",
            gists_url: "https://api.github.com/users/fargozhu/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/fargozhu",
            id: 904062,
            login: "fargozhu",
            node_id: "MDQ6VXNlcjkwNDA2Mg==",
            organizations_url: "https://api.github.com/users/fargozhu/orgs",
            received_events_url: "https://api.github.com/users/fargozhu/received_events",
            repos_url: "https://api.github.com/users/fargozhu/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/fargozhu/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/fargozhu/subscriptions",
            type: "User",
            url: "https://api.github.com/users/fargozhu"
          },
          description: "",
          due_on: nil,
          html_url: "https://github.com/cloudfoundry-incubator/kubecf/milestone/12",
          id: 5585831,
          labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12/labels",
          node_id: "MDk6TWlsZXN0b25lNTU4NTgzMQ==",
          number: 12,
          open_issues: 18,
          state: "open",
          title: "jumanji",
          updated_at: "2020-09-11T12:14:59Z",
          url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12"
        },
        node_id: "MDU6SXNzdWU2MjIwNzM5NzQ=",
        number: 905,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "Implement HA settings for Eirini",
        updated_at: "2020-09-04T01:54:03Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/905",
        user: %{
          avatar_url: "https://avatars3.githubusercontent.com/u/78947?v=4",
          events_url: "https://api.github.com/users/jandubois/events{/privacy}",
          followers_url: "https://api.github.com/users/jandubois/followers",
          following_url: "https://api.github.com/users/jandubois/following{/other_user}",
          gists_url: "https://api.github.com/users/jandubois/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/jandubois",
          id: 78947,
          login: "jandubois",
          node_id: "MDQ6VXNlcjc4OTQ3",
          organizations_url: "https://api.github.com/users/jandubois/orgs",
          received_events_url: "https://api.github.com/users/jandubois/received_events",
          repos_url: "https://api.github.com/users/jandubois/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/jandubois/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/jandubois/subscriptions",
          type: "User",
          url: "https://api.github.com/users/jandubois"
        }
      },
      %{
        active_lock_reason: nil,
        assignee: nil,
        assignees: [],
        author_association: "MEMBER",
        body: "**Describe the bug**\r\n\r\nSince Eirini apps cannot resolve the DNS records from the kubecf coreDNS instance, credhub.servie.cf.internal becomes unreachable.\r\n\r\n**To Reproduce**\r\n\r\nDeploy kubecf with Eirini and check that credhub CATS suite doesn't pass.\r\n\r\n**Expected behavior**\r\n\r\nEirini apps should be able to resolve the kubecf DNS entries. It may be possible with an EiriniX mutator.\r\n\r\n**Environment**\r\n\r\nAll versions.\r\n",
        closed_at: nil,
        comments: 9,
        comments_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/284/comments",
        created_at: "2019-12-21T00:54:53Z",
        events_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/284/events",
        html_url: "https://github.com/cloudfoundry-incubator/kubecf/issues/284",
        id: 541259800,
        labels: [
          %{
            color: "ffcc00",
            default: false,
            description: "",
            id: 1709895846,
            name: "Priority: Medium",
            node_id: "MDU6TGFiZWwxNzA5ODk1ODQ2",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Priority:%20Medium"
          },
          %{
            color: "0e8a09",
            default: false,
            description: "SUSE is pursuing a solution",
            id: 1672157281,
            name: "SUSE",
            node_id: "MDU6TGFiZWwxNjcyMTU3Mjgx",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/SUSE"
          },
          %{
            color: "296387",
            default: false,
            description: "Dependencies on other issues and/or pull requests",
            id: 1624005099,
            name: "Status: Blocked",
            node_id: "MDU6TGFiZWwxNjI0MDA1MDk5",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Status:%20Blocked"
          },
          %{
            color: "037ba3",
            default: false,
            description: "",
            id: 1624014462,
            name: "Status: WIP",
            node_id: "MDU6TGFiZWwxNjI0MDE0NDYy",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Status:%20WIP"
          },
          %{
            color: "d73a4a",
            default: false,
            description: "Something isn't working",
            id: 1621674803,
            name: "Type: Bug",
            node_id: "MDU6TGFiZWwxNjIxNjc0ODAz",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20Bug"
          },
          %{
            color: "c7edfc",
            default: false,
            description: "",
            id: 1700888071,
            name: "Type: Spike",
            node_id: "MDU6TGFiZWwxNzAwODg4MDcx",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/Type:%20Spike"
          },
          %{
            color: "001500",
            default: false,
            description: "",
            id: 2011893458,
            name: "suse-cap",
            node_id: "MDU6TGFiZWwyMDExODkzNDU4",
            url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/labels/suse-cap"
          }
        ],
        labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/284/labels{/name}",
        locked: false,
        milestone: %{
          closed_at: nil,
          closed_issues: 29,
          created_at: "2020-06-26T10:04:38Z",
          creator: %{
            avatar_url: "https://avatars2.githubusercontent.com/u/904062?v=4",
            events_url: "https://api.github.com/users/fargozhu/events{/privacy}",
            followers_url: "https://api.github.com/users/fargozhu/followers",
            following_url: "https://api.github.com/users/fargozhu/following{/other_user}",
            gists_url: "https://api.github.com/users/fargozhu/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/fargozhu",
            id: 904062,
            login: "fargozhu",
            node_id: "MDQ6VXNlcjkwNDA2Mg==",
            organizations_url: "https://api.github.com/users/fargozhu/orgs",
            received_events_url: "https://api.github.com/users/fargozhu/received_events",
            repos_url: "https://api.github.com/users/fargozhu/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/fargozhu/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/fargozhu/subscriptions",
            type: "User",
            url: "https://api.github.com/users/fargozhu"
          },
          description: "",
          due_on: nil,
          html_url: "https://github.com/cloudfoundry-incubator/kubecf/milestone/12",
          id: 5585831,
          labels_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12/labels",
          node_id: "MDk6TWlsZXN0b25lNTU4NTgzMQ==",
          number: 12,
          open_issues: 18,
          state: "open",
          title: "jumanji",
          updated_at: "2020-09-11T12:14:59Z",
          url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/milestones/12"
        },
        node_id: "MDU6SXNzdWU1NDEyNTk4MDA=",
        number: 284,
        performed_via_github_app: nil,
        repository_url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf",
        state: "open",
        title: "Make Eirini apps work with our DNS",
        updated_at: "2020-09-10T20:30:04Z",
        url: "https://api.github.com/repos/cloudfoundry-incubator/kubecf/issues/284",
        user: %{
          avatar_url: "https://avatars0.githubusercontent.com/u/3149049?v=4",
          events_url: "https://api.github.com/users/f0rmiga/events{/privacy}",
          followers_url: "https://api.github.com/users/f0rmiga/followers",
          following_url: "https://api.github.com/users/f0rmiga/following{/other_user}",
          gists_url: "https://api.github.com/users/f0rmiga/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/f0rmiga",
          id: 3149049,
          login: "f0rmiga",
          node_id: "MDQ6VXNlcjMxNDkwNDk=",
          organizations_url: "https://api.github.com/users/f0rmiga/orgs",
          received_events_url: "https://api.github.com/users/f0rmiga/received_events",
          repos_url: "https://api.github.com/users/f0rmiga/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/f0rmiga/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/f0rmiga/subscriptions",
          type: "User",
          url: "https://api.github.com/users/f0rmiga"
        }
      }
    ]
  end
end
